version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: "nuget"
    directory: "/Jellyfin.Plugin.YoutubeMetadata"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/Jellyfin.Plugin.YoutubeMetadata.Providers.Tests"
    schedule:
      interval: "weekly"
